### PR TITLE
Implement Toeplitz matrices

### LINKED ISSUE #1: Batch support & Backprop
First thanks a lot for the implementation, that's great !

Is there a plan to support batch computation? This would really be a game changer ! 

Regarding the backprop, the only op that prevents it is the toeplitz matrix in numpy right? 
I'm going to make a PR for the toeplitz matrix.

### PR DESCRIPTION
**Pull request by mpariente**
### About the PR

- [x] Implement Toeplitz matrices in `torch`
- [x] Implement batch Toeplitz matrices in `torch`
- [x] Unit test against `scipy`
- [ ] Use it in `separation.py`

### CODE REVIEW

**Comment by mpariente** [comment]
Let's merge this as is and make another PR to integrate it into `separation.py` WDYT?

**Comment by JuanFMontesinos** [comment]
Done at 0978b4e6492613a5efa6051e27c5f85fe0e9ccae

**Comment by mpariente** [comment]
Have you checked if it is backpropagable now?

**Comment by JuanFMontesinos** [comment]
Yes it is I imagine that at least sdr and sar. Since sri is sometimes inf and manually assigned I expect in those cases the graph to be broken. Anyway its better to avoid nans

**Pull request merged**
